[package]
name = "infire"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nfc1 = "0.4.1"
libaes = "0.6.4"
hex = "0.4.3"